### ISSUE TITLE
Docusaurus 3 example?

### ISSUE THREAD

**Issue by rewdy** [show-docs/remark-kroki#6]
This is not _strictly_ an issue, but looking for a little guidance. I'm trying to install/use this on a docusaurus 3 website. I'm getting a bunch of errors from webpack when I try to start up or build. I guess I'm wondering if you have a docusaurus 3 site with the plugin functioning that I could look at for reference? If so, I could maybe use that to debug what's wrong with my setup.

Thanks for your plugin!

If it's helpful, these are some of the errors:

```bash
Module not found: Error: Can't resolve 'process/browser' in '/Users/andrewmeyer/Workspace/front-end/portal/node_modules/node-fetch/src'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

Then a bunch of these for different `node:*` modules:

```bash
Module build failed: UnhandledSchemeError: Reading from "node:assert" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

**Comment by Airkro** [comment]
That error cause by other thing, not `remark-kroki`.

I create a minimal example [here](https://stackblitz.com/edit/github-edmah1?file=docusaurus.config.js), It's working well.

![image](https://github.com/user-attachments/assets/15a0d860-a7f5-4099-9163-d8cdb9a7f479)

**Comment by rewdy** [comment]
Thank you! I will review your example.
